import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { initialStateForUser } from "./repository/studentOsRepository.js";
import {
  buildDeterministicStudyMaterial,
  ensureDailyTodoStudyState,
  findDailyTodoItem,
  generateStudyMaterial,
  relatedMaterialsForTodo,
  updateDailyTodoStudyStatus,
} from "./ai/studyMaterialService.js";
import { CLASSROOM_WRITE_ACTIONS, canUseClassroomAction } from "./domain/planEntitlementService.js";
import { getProductFlowConfig } from "./domain/productLifecycleService.js";

const now = new Date("2026-07-05T10:00:00.000Z");
const state = initialStateForUser({ id: "phase21_student" });
state.courses.push({
  id: "course_physics",
  title: "Physics",
  source: "manual",
  academicContextIncluded: true,
  selectionState: "imported",
});
state.studentProfile.dailyTodoPlan = ensureDailyTodoStudyState({
  date: "2026-07-05",
  generated_at: now.toISOString(),
  items: [{
    title: "Review motion and forces",
    related_course: "Physics",
    related_context: "Newton's laws",
    reason: "The Physics exam is approaching.",
    time_hint: "45 minutes",
    priority: "high",
  }],
});

const item = state.studentProfile.dailyTodoPlan.items[0];
assert.match(item.id, /^todo_2026-07-05_1_/);
assert.equal(item.study_status, "not_started");
assert.equal(findDailyTodoItem(state, item.id), item);

updateDailyTodoStudyStatus(state, item.id, "studying", { now });
assert.equal(item.study_status, "studying");
updateDailyTodoStudyStatus(state, item.id, "done", { now });
assert.equal(item.study_status, "done");
assert.equal(item.study_completed_at, now.toISOString());
assert.equal(state.testSessions.length, 0, "marking study done must not start a strict test session");

const deterministic = buildDeterministicStudyMaterial(item);
for (const heading of [
  "Concept explanation",
  "Key formulas and relationships",
  "Worked example",
  "Common mistakes",
  "Practice checks",
  "Summary",
]) assert.match(deterministic, new RegExp(heading));
assert.doesNotMatch(deterministic, /answer key|grade this|submit/i);

const generated = await generateStudyMaterial({
  state,
  item,
  now,
  providerConfig: { requestedMode: "mock" },
});
assert.equal(generated.generationSucceeded, true);
assert.equal(generated.material.userId, state.studentProfile.id);
assert.equal(generated.material.courseId, "course_physics");
assert.equal(generated.material.todoItemId, item.id);
assert.equal(generated.material.source, "studentos_generated");
assert.equal(generated.material.academicContextIncluded, true);
assert.equal(generated.material.selectionState, "imported");
assert.equal(generated.material.generatedAt, now.toISOString());
state.sourceMaterials.push(generated.material);
item.generated_material_id = generated.material.id;
assert.equal(relatedMaterialsForTodo(state, item)[0].id, generated.material.id);

const [html, app, server, authorizedAiExecution, css, packageJson] = await Promise.all([
  readFile(new URL("../frontend/index.html", import.meta.url), "utf8"),
  readFile(new URL("../frontend/scripts/app.js", import.meta.url), "utf8"),
  readFile(new URL("./server.js", import.meta.url), "utf8"),
  readFile(new URL("./ai/authorizedAiExecutionService.js", import.meta.url), "utf8"),
  readFile(new URL("../frontend/styles/main.css", import.meta.url), "utf8"),
  readFile(new URL("../package.json", import.meta.url), "utf8"),
]);

const navStart = html.indexOf('aria-label="Views"');
const nav = html.slice(navStart, html.indexOf("</nav>", navStart));
assert(nav.indexOf("Academic Context") < nav.indexOf("Study and Evaluate"));
assert(nav.indexOf("Study and Evaluate") < nav.indexOf("Studio"));
for (const copy of [
  "Study the next item from your plan, then check yourself when you are ready.",
  "Generate today's TO-DO list first.",
  "Choose what you want to study now.",
  "No study note is available yet.",
  "Generate note",
  "Mark note done",
  "Generate test",
]) assert.match(`${html}\n${app}`, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));

assert.match(app, /state\.todayPlan/);
assert.match(app, /data-study-item-id/);
assert.match(app, /Open material/);
assert.match(app, /Generated by StudentOS/);
assert.match(app, /Saved to Academic Context/);
assert.match(css, /\.study-evaluate-content/);
assert.match(server, /url\.pathname === "\/api\/study\/material"/);
assert.match(server, /executeAuthorizedAiOperation\([\s\S]*workflow: "study_material"/);
assert.match(authorizedAiExecution, /reserveAiWeeklyAllowance/);
assert.match(authorizedAiExecution, /settleAiWeeklyAllowance/);
assert.match(server, /state\.sourceMaterials\.push\(result\.material\)/);
assert.match(server, /testSessionStarted: false/);
assert.match(server, /\/api\/study\/test/);
assert.match(packageJson, /test:phase2-1/);

const normalStudyHtml = html.slice(html.indexOf('id="view-study"'), html.indexOf('id="view-studio"'));
assert.doesNotMatch(normalStudyHtml, /\b(?:provider|model|token|storage|database|backend|vector|embedding|chunks?|debug|OAuth scope)\b/i);
assert.doesNotMatch(`${html}\n${app}`, /Plan Free/i);
for (const plan of ["trial", "starter", "essential", "plus", "pro"]) {
  for (const action of CLASSROOM_WRITE_ACTIONS) assert.equal(canUseClassroomAction(plan, action), false);
}
assert.equal(getProductFlowConfig({}, "development").realPaymentEnabled, false);

console.log("PASS | StudentOS Phase 2.1 Study and Evaluate foundation tests passed");
